CLASS DumbassShitFuckDickCockShotgun : Shotgun replaces Shotgun { 
	Default {
		Weapon.SelectionOrder 1300;
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 8;
		Weapon.AmmoType "Shell";
		Weapon.AmmoType2 "Shell";
		Inventory.PickupMessage "$GOTDSFDCSHOTGUN";
		Obituary "$OB_DSFDCSHOTGUN";
		Tag "$TAG_DSFDCSHOTGUN";
	}
	States
	{
		Ready:
			SHTG A 1 A_WeaponReady;
			Loop;
		Deselect:
			SHTG A 1 A_Lower(18);
			Loop;
		Select:
			SHTG A 1 A_Raise(18);
			Loop;
		Fire:
			SHTG A 0 A_JumpIfInventory("SpanishFist", 1, "FireSailor");
			SHTG A 0 A_JumpIfInventory("CocainePower", 1, "FireCocaine");
			SHTS A 0
			{
			    A_Quake(1,4,0,100);
			    A_FireBullets(100, 100, 1000, random(1,5), "BulletPuff", FBF_USEAMMO|FBF_NORANDOM);
			    A_StartSound("weapons/sshotf", CHAN_WEAPON);
			    A_GunFlash();
			    A_Recoil(80);
			}
			SHTS A 1 A_SetPitch(pitch-5);
			SHTS AAAB 1 A_SetPitch(pitch+1);
			SHTS B 0
			{
			    A_Quake(1,4,0,100);
			    A_FireBullets(50, 50, 500, 2, "BulletPuff", FBF_USEAMMO|FBF_NORANDOM);
			    A_StartSound("weapons/sshotf", CHAN_WEAPON);
			    A_GunFlash();
			    A_Recoil(40);
			}
			SHTS B 1 A_SetPitch(pitch-5);
			SHTS BBCC 1 A_SetPitch(pitch+1);
			SHTS C 0
			{
			    A_FireBullets(10, 10, 100, 2, "BulletPuff", FBF_USEAMMO|FBF_NORANDOM);
			    A_StartSound("weapons/sshotf", CHAN_WEAPON);
			    A_GunFlash();
			}
			SHTS C 4;
			SHTS ABCABCABC 4;
			SHTG B 3 A_StartSound("DSCOCKA", CHAN_WEAPON);
			SHTG C 3;
			SHTG D 3 A_StartSound("DSCOCKB", CHAN_WEAPON);
			SHTG CB 3;
			SHTG A 7 A_ReFire;
			Goto Ready;
		FireCocaine:
			SHTS A 0
			{
			    A_Quake(1,4,0,100);
			    A_FireBullets(100, 100, 1000, random(1,2), "BulletPuff", FBF_USEAMMO|FBF_NORANDOM);
			    A_StartSound("weapons/sshotf", CHAN_WEAPON);
			    A_GunFlash();
			    A_Recoil(80);
			}
			SHTS A 1 A_SetPitch(pitch-5);
			SHTS AAAB 1 A_SetPitch(pitch+1);
			SHTS B 0
			{
			    A_Quake(1,4,0,100);
			    A_FireBullets(50, 50, 500, 1, "BulletPuff", FBF_USEAMMO|FBF_NORANDOM);
			    A_StartSound("weapons/sshotf", CHAN_WEAPON);
			    A_GunFlash();
			    A_Recoil(40);
			}
			SHTS B 1 A_SetPitch(pitch-5);
			SHTS BBCC 1 A_SetPitch(pitch+1);
			SHTS C 0
			{
			    A_FireBullets(10, 10, 100, 1, "BulletPuff", FBF_USEAMMO|FBF_NORANDOM);
			    A_StartSound("weapons/sshotf", CHAN_WEAPON);
			    A_GunFlash();
			}
			SHTS C 2;
			SHTS A 5;
			SHTG B 2 A_StartSound("DSCOCKA", CHAN_WEAPON);
			SHTG C 2;
			SHTG D 2 A_StartSound("DSCOCKB", CHAN_WEAPON);
			SHTG CB 2;
			SHTG A 4 A_ReFire;
			Goto Ready;
		FireSailor:
			SHTG A 0 A_JumpIfInventory("CocainePower", 1, "FireSailorCocaine");
			SHTG A 2
			{
			  A_FireBullets (5.6,5.6,10,random(7,11),"BulletPuff",FBF_USEAMMO|FBF_NORANDOM);
			  A_StartSound("weapons/autoshotgun", CHAN_WEAPON);
			  A_GunFlash();
			  A_WeaponOffset(0.0, 48.0, WOF_INTERPOLATE);
			  A_Recoil(5);
			}
			SHTG A 2 A_WeaponOffset(0.0, 44.0, WOF_INTERPOLATE);
			SHTG A 2 A_WeaponOffset(0.0, 36.0, WOF_INTERPOLATE);
			SHTG A 2 A_WeaponOffset(0.0, 32.0, WOF_INTERPOLATE);
			Goto Ready;
		FireSailorCocaine:
			SHTG A 2
			{
			  A_FireBullets (5.6,5.6,20,random(21,33),"BulletPuff",FBF_USEAMMO|FBF_NORANDOM);
			  A_StartSound("weapons/m3", CHAN_WEAPON);
			  A_GunFlash();
			  A_WeaponOffset(0.0, 56.0, WOF_INTERPOLATE);
			  A_Recoil(10);
			}
			SHTG A 2 A_WeaponOffset(0.0, 52.0, WOF_INTERPOLATE);
			SHTG A 2 A_WeaponOffset(0.0, 36.0, WOF_INTERPOLATE);
			SHTG A 2 A_WeaponOffset(0.0, 32.0, WOF_INTERPOLATE);
			Goto Ready;
		Flash:
			SHTF B 1 Bright A_Light2;
			SHTF A 1 Bright A_Light1;
			Goto LightDone;
		AltFlash:
			SHTF B 1 Bright A_Light2;
			SHTF A 1 Bright A_Light1;
			Goto LightDone;
		Spawn:
			SHOT A -1;
			Stop;
	}
}

CLASS SmallButPackingChaingun : Chaingun replaces Chaingun { 
	Default {
		Weapon.BobRangeX 0.75;
		Weapon.BobRangeY 0.25;
		Weapon.BobSpeed 0.75 ;
		Weapon.KickBack 1000;
		Weapon.SelectionOrder 700;
		Weapon.AmmoUse 5;
		Weapon.AmmoGive 100;
		Weapon.AmmoType "Clip";
		Inventory.PickupMessage "$GOTOVERCHARGEDMINIGUN";
		Obituary "$OB_OVERCHARGEDMINIGUN";
		Tag "$TAG_OVERCHARGEDMINIGUN";
	}
	States
	{
		Ready:
			CHGG A 1 A_WeaponReady;
			Loop;
		Deselect:
			CHGG A 1 A_Lower(18);
			Loop;
		Select:
			CHGG A 1 A_Raise(18);
			Loop;
		Fire:
			CHGG A 0 A_JumpIfInventory("CocainePower", 1, "FireCocaine");
			TNT1 A 0 A_GunFlash;
			CHGG AB 2
			{
			    A_FireBullets(7, 2.8, 10, random(20,30), "BulletPuff", FBF_USEAMMO|FBF_NORANDOM);
			    A_Recoil(2);
			    A_StartSound("weapons/m249", CHAN_WEAPON);
			}
			CHGG ABABABAB 2 A_ReFire;
			CHGG ABAB 4 A_ReFire;
			CHGG AB 6;
			Goto Ready;
		FireCocaine: 
			TNT1 A 0 A_GunFlash("FlashCocaine");
			CHGG AB 1
			{
			    A_FireBullets(10, 4, 20, random(50,200), "BulletPuff", FBF_USEAMMO|FBF_NORANDOM);
			    A_Recoil(4);
			    A_StartSound("weapons/m249", CHAN_WEAPON);
			}
			CHGG ABABABAB 1 A_ReFire;
			CHGG ABAB 2 A_ReFire;
			CHGG AB 3;
			Goto Ready;
		Flash:
			CHGF A 2 Bright A_Light1;
			CHGF B 2 Bright A_Light1;
			Goto LightDone;
		FlashCocaine:
			CHGF A 1 Bright A_Light1;
			CHGF B 1 Bright A_Light1;
			Goto LightDone;
		Spawn:
			MGUN A -1;
			Stop;
	}
}

CLASS SingularBullet : Weapon { 
	double angley;
	Default {
		Weapon.SelectionOrder 3700;
		Weapon.Kickback 100;
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 1;
		Weapon.AmmoType "Clip";
		Weapon.AmmoUse2 1;
		Weapon.AmmoType2 "Clip";
		Inventory.PickupMessage "$GOTSINGULARBULLET" ;
		Obituary "$OB_SINGULARBULLET";
		Tag "$TAG_SINGULARBULLET";
		+WEAPON.ALT_AMMO_OPTIONAL
		+weapon.wimpy_weapon
	}
	States
	{
		Ready: 
			PUNG A 1 A_WeaponReady;
			Loop;
		Deselect:
			PUNG A 1 A_Lower(18);
			Loop;
		Select:
			PUNG A 1 A_Raise(18);
			Loop;
		Fire:
			PUNG A 0 A_JumpIfInventory("CocainePower", 1, "FireCocaine");
			BULP HIJABCD 1;
			BULP E 0
			{
			    A_StartSound("*fist", CHAN_AUTO);
			    A_StartSound("weapons/pistol", CHAN_WEAPON);
			}
			BULP E 2 A_FireBullets(0, 0, 1, random(20,50), "BulletPuff", FBF_USEAMMO|FBF_NORANDOM);
			BULP FG 1;
			PUNG A 1 A_ReFire;
			Goto Ready;
		FireCocaine:
			BULP HJB 1;
			BULP E 0
			{
			    A_StartSound("*fist", CHAN_AUTO);
			    A_StartSound("weapons/pistol", CHAN_WEAPON);
			}
			BULP E 1 A_FireBullets(1, 1, 3, random(50,200), "BulletPuff", FBF_USEAMMO|FBF_NORANDOM);
			BULP FG 1;
			PUNG A 1 A_ReFire;
			Goto Ready;
		AltFire:
			OIJG A 0 A_JumpIfInventory("CocainePower", 1, "AltFireCocaine");
			OIJG A 2 { A_StartSound("skeleton/swing"); invoker.angley = -6; }
			OIJG BBCC 1 {
				if(countinv("clip"))A_FireProjectile("ThrownBullet",invoker.angley,true); invoker.angley++;
				if(countinv("clip"))A_FireProjectile("ThrownBullet",invoker.angley,true); invoker.angley++;
				
			}
			OIJG D 1 {
				if(countinv("clip"))A_FireProjectile("ThrownBullet",invoker.angley,true); invoker.angley++;
				if(countinv("clip"))A_FireProjectile("ThrownBullet",invoker.angley,true); invoker.angley++;
				A_CustomPunch(random(5,15), false, 0, "BulletPuff", 70,0,0,"ArmorBonus","HOWCANSHESLAP");
			}
			OIJG D 1 {
				if(countinv("clip"))A_FireProjectile("ThrownBullet",invoker.angley,true); invoker.angley++;
				if(countinv("clip"))A_FireProjectile("ThrownBullet",invoker.angley,true); invoker.angley++;
				
			}
			OIJG E 2;
			OIJG F 2 A_ReFire;
			Goto Ready;
		AltFireCocaine:
			OIJG A 1 { A_StartSound("skeleton/swing"); invoker.angley = -6; }
			OIJG BC 1 {
				for(int i = 1; i <= 4; i++) {
					if(countinv("clip"))A_FireProjectile("ThrownBulletCrack",invoker.angley,true); invoker.angley++;
				}
			}
			OIJG D 1 {
				for(int i = 1; i <= 4; i++) {
					if(countinv("clip"))A_FireProjectile("ThrownBulletCrack",invoker.angley,true); invoker.angley++;
				}
				A_CustomPunch(random(40,120), false, 0, "BulletPuff", 70,0,0,"ArmorBonus","HOWCANSHESLAP");
			}
			OIJG E 1;
			OIJG F 1 A_ReFire;
			Goto Ready;
		Spawn:
			BULL A -1;
			Loop;
	}
}

class ThrownBullet : actor {
	default {
		Radius 8;
		Height 8;
		Speed 52;
		DamageFunction (random(16,40));
		Projectile;
		scale 1.25;
		-NOGRAVITY
		+bounceonactors
		BounceType "Doom";
		bouncecount 16;
		DeathSound "weapons/pistol";
		BounceSound "weapons/pistol";
		Gravity 0.5;
		Obituary "$OB_SINGULARBULLET";
	}
	states {
		spawn:
			bull a 1;
			loop;
		death:
			puff a 2 bright;
			puff bcd 2;
			stop;
	}
}

class ThrownBulletCrack : ThrownBullet {
	default {
		damagefunction (random(32,96));
		scale 2;
	}
}

CLASS DuperShotgun : SuperShotgun replaces SuperShotgun { 
	Default {
		Weapon.SelectionOrder 400;
		Weapon.AmmoUse1 6;
		Weapon.AmmoUse2 12;
		Weapon.AmmoGive 12;
		Weapon.AmmoType1 "Shell";
		Weapon.AmmoType2 "Shell";
		Inventory.PickupMessage "$GOTDUPERSHOTGUN";
		Obituary "$OB_DUPERSHOTGUN";
		Tag "$TAG_DUPERSHOTGUN";
	}
	States
	{
		Ready:
			SHT2 A 1 A_WeaponReady;
			Loop;
		Deselect:
			SHT2 A 1 A_Lower(18);
			Loop;
		Select:
			SHT2 A 1 A_Raise(18);
			Loop;
		Fire:
			SHT2 A 0 A_JumpIfInventory("CocainePower", 1, "FireCocaine");
			SHT2 A 3;
			SHT2 A 0
			{
			    A_Quake(6,12,0,800);
			    A_FireBullets (12, 7, 40, 75, "BulletPuff", FBF_USEAMMO|FBF_NORANDOM);
			    A_StartSound ("weapons/sshotf", CHAN_WEAPON);
			    A_GunFlash();
			    A_Recoil(160);
			}
			SHT2 A 1 A_SetPitch(pitch-40);
			SHT2 AAAAAA 1 A_SetPitch(pitch+6);
			SHT2 B 7;
			SHT2 C 7 A_CheckReload;
			SHT2 D 4 A_OpenShotgun2;
			SHT2 E 4;
			SHT2 F 4 A_LoadShotgun2;
			SHT2 DE 4;
			SHT2 F 4 A_LoadShotgun2;
			SHT2 DE 4;
			SHT2 F 4 A_LoadShotgun2;
			SHT2 DE 3;
			SHT2 F 3 A_LoadShotgun2;
			SHT2 DE 3;
			SHT2 F 3 A_LoadShotgun2;
			SHT2 DE 3;
			SHT2 F 3 A_LoadShotgun2;
			SHT2 G 6;
			SHT2 H 6 A_CloseShotgun2;
			SHT2 A 5 A_ReFire;
			Goto Ready;
		FireCocaine:
			SHT2 A 2;
			SHT2 A 0
			{
			    A_Quake(6,12,0,800);
			    A_FireBullets (12, 7, 80, 150, "BulletPuff", FBF_USEAMMO|FBF_NORANDOM);
			    A_StartSound ("weapons/sshotf", CHAN_WEAPON);
			    A_GunFlash();
			    A_Recoil(160);
			}
			SHT2 A 1 A_SetPitch(pitch-40);
			SHT2 AAAAAA 1 A_SetPitch(pitch+6);
			SHT2 B 2;
			SHT2 C 2 A_CheckReload;
			SHT2 D 2 A_OpenShotgun2;
			SHT2 E 2;
			SHT2 F 2 A_LoadShotgun2;
			SHT2 DE 2;
			SHT2 F 1 A_LoadShotgun2;
			SHT2 DE 1;
			SHT2 F 1 A_LoadShotgun2;
			SHT2 DE 1;
			SHT2 F 1 A_LoadShotgun2;
			SHT2 DE 1;
			SHT2 F 1 A_LoadShotgun2;
			SHT2 DE 1;
			SHT2 F 1 A_LoadShotgun2;
			SHT2 G 1;
			SHT2 H 2 A_CloseShotgun2;
			SHT2 A 3 A_ReFire;
			Goto Ready;
		AltFire:
			SHT2 A 0 A_JumpIfInventory("CocainePower", 1, "AltFireCocaine");
			SHT2 A 3;
			SHD2 EDCBA 3;
			SHD2 F 0
			{
			    A_Quake(8,12,0,1000);
			    A_FireBullets (32, 24, 80, 75, "BulletPuff", FBF_USEAMMO|FBF_NORANDOM);
			    A_StartSound ("weapons/sshotf", CHAN_WEAPON);
			    A_GunFlash();
			    A_Recoil(320);
			}
			SHD2 A 1 A_SetPitch(pitch-60);
			SHD2 AAFFFAAAAA 1 A_SetPitch(pitch+6);
			SHD2 A 7;
			SHD2 ABCDE 2;
			SHT2 AB 2;
			SHT2 C 7 A_CheckReload;
			SHT2 D 4 A_OpenShotgun2;
			SHT2 E 4;
			SHT2 F 4 A_LoadShotgun2;
			SHT2 DE 4;
			SHT2 F 4 A_LoadShotgun2;
			SHT2 DE 4;
			SHT2 F 4 A_LoadShotgun2;
			SHT2 DE 3;
			SHT2 F 3 A_LoadShotgun2;
			SHT2 DE 3;
			SHT2 F 3 A_LoadShotgun2;
			SHT2 DE 3;
			SHT2 F 3 A_LoadShotgun2;
			SHT2 DE 2;
			SHT2 F 2 A_LoadShotgun2;
			SHT2 DE 2;
			SHT2 F 2 A_LoadShotgun2;
			SHT2 DE 2;
			SHT2 F 2 A_LoadShotgun2;
			SHT2 DE 2;
			SHT2 F 2 A_LoadShotgun2;
			SHT2 DE 1;
			SHT2 F 1 A_LoadShotgun2;
			SHT2 G 6;
			SHT2 H 6 A_CloseShotgun2;
			SHT2 A 5 A_ReFire;
			Goto Ready;
		AltFireCocaine:
			SHT2 A 1;
			SHD2 EDCBA 1;
			SHD2 F 0
			{
			    A_Quake(8,12,0,1000);
			    A_FireBullets (32, 24, 160, 300, "BulletPuff");
			    A_StartSound ("weapons/sshotf", CHAN_WEAPON);
			    A_GunFlash();
			    A_Recoil(320);
			}
			SHD2 A 1 A_SetPitch(pitch-60);
			SHD2 AFAA 1 A_SetPitch(pitch+12);
			SHD2 A 1;
			SHD2 ABCDE 2;
			SHT2 AB 2;
			SHT2 C 1 A_CheckReload;
			SHT2 D 1 A_OpenShotgun2;
			SHT2 E 1;
			SHT2 F 1 A_LoadShotgun2;
			SHT2 DE 1;
			SHT2 F 1 A_LoadShotgun2;
			SHT2 DE 1;
			SHT2 F 1 A_LoadShotgun2;
			SHT2 DE 1;
			SHT2 F 1 A_LoadShotgun2;
			SHT2 DE 1;
			SHT2 F 1 A_LoadShotgun2;
			SHT2 DE 1;
			SHT2 F 1 A_LoadShotgun2;
			SHT2 DE 1;
			SHT2 F 1 A_LoadShotgun2;
			SHT2 DE 1;
			SHT2 F 1 A_LoadShotgun2;
			SHT2 DE 1;
			SHT2 F 1 A_LoadShotgun2;
			SHT2 DE 1;
			SHT2 F 1 A_LoadShotgun2;
			SHT2 DE 1;
			SHT2 F 1 A_LoadShotgun2;
			SHT2 G 1;
			SHT2 H 2 A_CloseShotgun2;
			SHT2 A 3 A_ReFire;
			Goto Ready;
		Flash:
			SHT2 I 4 Bright A_Light1;
			SHT2 J 3 Bright A_Light2;
			Goto LightDone;
		AltFlash:
			SHE2 A 1 Bright A_Light1;
			SHE2 B 2 Bright A_Light2;
			Goto LightDone;	
		Spawn:
			SGN2 A -1;
			Stop;
	}
}

CLASS Cocaine : Berserk replaces Berserk { 
	Default {
		+COUNTITEM;
		+INVENTORY.ALWAYSPICKUP;
		Inventory.PickupMessage "$GOTCOCAINE";
		Inventory.PickupSound "cocaine/pickup";
		Tag "Cocaine";
	}
	States
	{
		Spawn:
			PSTR A -1;
			Stop;
		Pickup:
			TNT1 A 0 A_GiveInventory("CocainePower");
			TNT1 A 0 HealThing(150, 2500);
			Stop;
	}
}

CLASS CocainePower : Powerup { 
	Default {
		Powerup.Duration -90;
		Powerup.Color "255, 0, 128, 0.25";
		+INVENTORY.HUBPOWER;
	}
}

CLASS SawSaw : Chainsaw replaces Chainsaw { 
	//defined when the sawsaw sound starts
	int loops;
	Default {
		Weapon.Kickback -100;
		Weapon.SelectionOrder 2200;
		Weapon.UpSound "";
		Weapon.ReadySound "";
		Inventory.PickupMessage "$GOTSAWSAW";
		Obituary "$OB_SAWSAW";
		Tag "$TAG_SAWSAW";
		+WEAPON.MELEEWEAPON;
	}
	States
	{
		Ready:
			SAWG C 1 A_WeaponReady;
			Loop;
		Deselect:
			SAWG C 1 A_Lower(18);
			Loop;
		Select:
			SAWG C 1 A_Raise(18);
			Loop;
		Fire:
			SAWG C 0 A_JumpIfInventory("CocainePower", 1, "FireCocaine");
			SAWG C 2
			{
				A_Saw("","",1);
				A_StartSound("sawfail", CHAN_AUTO, CHANF_OVERLAP);
			}
			SAWG DCDCDC 2;
			SAWG DCDCD 4;
			SAWG C 2;
			SAWG C 2
			{
				A_Saw("","",1);
				A_StartSound("sawfail", CHAN_AUTO, CHANF_OVERLAP);
			}
			SAWG DCDCDC 2;
			SAWG DCDCD 4;
			SAWG C 2;
			SAWG C 2
			{
				A_Saw("","",1);
				A_StartSound("sawfail", CHAN_AUTO, CHANF_OVERLAP);
			}
			SAWG DCDCDC 2;
			SAWG DCDCD 4;
			SAWG C 2;
			SAWG C 2
			{
				A_Saw("","",1);
				A_StartSound("sawfail", CHAN_AUTO, CHANF_OVERLAP);
			}
			SAWG DCDC 4;
			SAWG B 0
			{
				A_StartSound("DSSAWSAW", CHAN_AUTO, CHANF_OVERLAP);
				invoker.loops=125; //how many times to loop
			}
		Looper:
			SAWG A 1
			{
				A_Recoil(-5);
				A_Saw("","misc/gibbed",100);
			}
			SAWG B 1
			{
				A_Recoil(-5);
				A_Saw("","misc/gibbed",100);
			}
			SAWG B 0
			{
				if (--invoker.loops != 0)
				{
				return ResolveState("Looper");
				}
				A_ReFire();
				return ResolveState("Ready");
			}
		FireCocaine:
			SAWG C 1
			{
				A_Saw("","",5);
				A_StartSound("sawfail", CHAN_AUTO, CHANF_OVERLAP);
			}
			SAWG DCDCDC 1;
			SAWG C 1
			{
				A_Saw("","",5);
				A_StartSound("sawfail", CHAN_AUTO, CHANF_OVERLAP);
			}
			SAWG DCDCDC 1;
			SAWG C 1
			{
				A_Saw("","",5);
				A_StartSound("sawfail", CHAN_AUTO, CHANF_OVERLAP);
			}
			SAWG DCDCDC 1;
			SAWG C 1
			{
				A_Saw("","",5);
				A_StartSound("sawfail", CHAN_AUTO, CHANF_OVERLAP);
			}
			SAWG DCDCDC 1;
			SAWG B 0
			{
				A_StartSound("DSSAWSAW", CHAN_AUTO, CHANF_OVERLAP);
				invoker.loops=125; //how many times to loop
			}
			Goto Looper;
		Spawn:
			CSAW A -1;
			Stop;
	}
}

CLASS Fucket : Rocket replaces Rocket { 
	Default {
		-ROCKETTRAIL;
		-DEHEXPLOSION;
		Speed 20;
		DamageFunction (random(60,70));
		Obituary "$OB_CORPSE";
		DeathSound "*fist" ;
		species "fucket";
		+THRUSPECIES;
	}
	States
	{
		Spawn:
			DEBI L 1 Bright;
			Loop;
		Death:
			MISL B 0 Bright A_Scream;
			MISL B 0 Bright A_SpawnItemEx("FuckedMarine") ;
			Stop;
	}
}

CLASS ImpactFucket : Rocket { 
	Default {
		-ROCKETTRAIL;
		Speed 48;
		DamageFunction (random(60,70));
		+FORCERADIUSDMG
		DamageType "fucket";
		Obituary "$OB_CORPSE";
	}
	States
	{
		Spawn:
			DEBI L 1 Bright;
			Loop;
		Death:
			DEBI L 0 {
				A_Explode(192,192,damagetype:"fucket");
				A_SetScale(1.25);
				A_Quake(2,8,0,400);
			}
			MISL BCD 4 Bright;
			Stop;
	}
}

CLASS NuclearActualFucket : Fucket { 
	States
	{
		Spawn:
			DEBI M 1 Bright;
			Loop;
		Death:
			MISL B 0 Bright A_Scream;
			MISL B 0 Bright A_SpawnItemEx("NuclearMarine") ;
			Stop;
	}
}

CLASS ImpactNuclearFucket : ImpactFucket { 
	States
	{
		Spawn:
			DEBI M 1 Bright;
			Loop;
		Death:
			PLAY WWWWWWWWWWWW 0 Bright A_SpawnItemEx("ThatThingThatGoesBoom",random(-3,3),random(-3,3),random(-3,3),random(-10,10),random(-10,10),random(-10,10));
			Stop;
	}
}

CLASS FuckedMarine : GibbedMarine replaces GibbedMarineExtra { 
	Default {
//		+PUSHABLE;
		+SHOOTABLE;
		+NOTAUTOAIMED;
		Health 10;
		pushfactor 0.1;
		Obituary "$OB_CORPSEBOOM";
		DeathSound "misc/gibbed";
		Tag "Fucked fucket";
		species "fucket";
		+THRUSPECIES;
	}
	States
	{
		Spawn:
			DEBI L 1000;
			GoTo Death;
		Death:
			PLAY W 0
			{
			    A_SpawnItemEx("ThatThingThatGoesBoom");
			    A_Scream();
			}
			PLAY W -1;
			Stop;
		Death.fucket:
			PLAY W 0
			{
			    A_SpawnItemEx("ThatThingThatGoesBoomMore");
			    A_Scream();
			}
			PLAY W -1;
			Stop;		
	}
}

CLASS NuclearMarine : FuckedMarine { 
	States
	{
		Spawn:
			DEBI M 1000;
			GoTo Death;
		Death:
			PLAY WWWWWWWWWWWW 0 Bright A_SpawnItemEx("ThatThingThatGoesBoom",random(-3,3),random(-3,3),random(-3,3),random(-10,10),random(-10,10),random(-10,10));
			PLAY W 0 A_Scream;
			PLAY W -1;
			Stop;
		Death.fucket:
			PLAY WWWWWWWWWWWW 0 Bright A_SpawnItemEx("ThatThingThatGoesBoomMore",random(-3,3),random(-3,3),random(-3,3),random(-10,10),random(-10,10),random(-10,10));
			PLAY W 0 A_Scream;
			PLAY W -1;
			Stop;
	}
}

CLASS ThatThingThatGoesBoom : ACTOR { 
	Default {
		Radius 11;
		Height 8;
		Speed 0;
		Damage 20;
		Projectile;
		+RANDOMIZE;
		+DEHEXPLOSION;
		-ROCKETTRAIL;
		+FORCERADIUSDMG;
		DeathSound "weapons/rocklx";
		Obituary "$OB_CORPSEBOOM";
	}
	States
	{
		Spawn:
			MISL A 1 Bright;
		Death:
			MISL B 0 Bright A_Scream;
			MISL B 0 A_Quake(2,8,0,400);
			MISL B 8 Bright A_Explode;
			MISL C 6 Bright;
			MISL D 4 Bright;
			Stop;
	}
}

class thatthingthatgoesboommore : thatthingthatgoesboom
{
	default { scale 1.25; damagetype "fucket"; }
	states
	{
		Death:
			MISL B 0 Bright A_Scream;
			MISL B 0 A_Quake(2,8,0,400);
			MISL B 8 Bright A_Explode(256,256);
			MISL C 6 Bright;
			MISL D 4 Bright;
			Stop;
	}
}

CLASS BCG9000 : BFG9000 replaces BFG9000 { 
	Default {
		Height 20;
		Weapon.SelectionOrder 2800;
		Weapon.AmmoUse 100;
		Weapon.AmmoGive 200;
		Weapon.AmmoType "Cell";
		+WEAPON.NOAUTOFIRE;
		Inventory.PickupMessage "$GOTSBFKAG";
		Tag "$TAG_SBFKAG";
		Obituary "$OB_SBFKAG";
	}
	States
	{
		Ready:
			BFGG A 1 A_WeaponReady;
			Loop;
		Deselect:
			BFGG A 1 A_Lower(18);
			Loop;
		Select:
			BFGG A 1 A_Raise(18);
			Loop;
		Fire:
			BFGG A 0 A_JumpIfInventory("CocainePower", 1, "FireCocaine");
			BFGG A 35 A_BFGSound;
			BFGG B 0
			{
			    A_Quake(8,12,0,1000);
			    A_FireBullets (64, 48, 160, random(25,100),"BulletPuff", FBF_USEAMMO|FBF_NORANDOM);
			    A_StartSound("Sraka",CHAN_AUTO,CHANF_DEFAULT,1.0,ATTN_NORM,0.75);
			    A_GunFlash();
			    A_Recoil(320);
                A_RailAttack(random(1000,2000),0,false);
				A_FireProjectile("BFGBall", -15, false);
				A_FireProjectile("BFGBall", 0, false);
				A_FireProjectile("BFGBall", 15, false);
			}
			BFGG BBBBBBBBBBBBBBBBBBBB 0
			{
				A_FireProjectile("BCGPlasmaBall",random(-75,75),false,0,0,0,random(-22.5,22.5));
				A_FireProjectile("BCGPlasmaBall",random(-45,45),false,0,0,0,random(-15,15));	
				A_FireProjectile("BCGPlasmaBall",random(-75,75),false,0,0,0,random(-22.5,22.5));
				A_FireProjectile("BCGPlasmaBall",random(-45,45),false,0,0,0,random(-15,15));
				A_FireProjectile("BCGPlasmaBall",random(-22.5,22.5),false,0,0,0,random(-7.5,7.5));
			}
			BFGG B 35;
			BFGG B 0 A_Refire();
			Goto Ready;
		FireCocaine:
			BFGG A 10 A_BFGSound;
			BFGG B 0
			{
			    A_Quake(8,12,0,1000);
			    A_FireBullets (96, 64, 320, random(100,400),"BulletPuff", FBF_USEAMMO|FBF_NORANDOM);
			    A_StartSound("Sraka",CHAN_AUTO,CHANF_DEFAULT,1.0,ATTN_NORM,0.75);
			    A_GunFlash();
			    A_Recoil(320);
                A_RailAttack(random(4000,8000),0,false);
				A_FireProjectile("BFGBall", -45, false);
				A_FireProjectile("BFGBall", -30, false);
				A_FireProjectile("BFGBall", -15, false);
				A_FireProjectile("BFGBall", 0, false);
				A_FireProjectile("BFGBall", 15, false);
				A_FireProjectile("BFGBall", 30, false);
				A_FireProjectile("BFGBall", 45, false);
			}
			BFGG BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 0
			{
				A_FireProjectile("BCGPlasmaBall",random(-75,75),false,0,0,0,random(-22.5,22.5));
				A_FireProjectile("BCGPlasmaBall",random(-45,45),false,0,0,0,random(-15,15));	
				A_FireProjectile("BCGPlasmaBall",random(-75,75),false,0,0,0,random(-22.5,22.5));
				A_FireProjectile("BCGPlasmaBall",random(-45,45),false,0,0,0,random(-15,15));
				A_FireProjectile("BCGPlasmaBall",random(-22.5,22.5),false,0,0,0,random(-7.5,7.5));
			}
			BFGG B 10;
			BFGG B 0 A_Refire();
			Goto Ready;
		Flash:
			BFGF A 11 Bright A_Light1;
			BFGF B 6 Bright A_Light2;
			Goto LightDone;
		Spawn:
			BFUG A -1;
			Stop;
	}
}

CLASS BCGPlasmaBall : PlasmaBall
{
	Default
	{
		SeeSound "";
		Obituary "$OB_SBFKAG";
	}
}

CLASS RechargablePlasmaRifleModelv1 : PlasmaRifle replaces PlasmaRifle { 
	Default {
		Weapon.SelectionOrder 9999;
		Weapon.AmmoUse 300;
		Weapon.AmmoGive 300;
		Weapon.AmmoType "Cell";
		Inventory.PickupMessage "$GOTOPRM";
		Tag "$TAG_OPRM";
		+WEAPON.NOAUTOFIRE
	}
	States
	{
		Ready:
			PLSG A 1 A_WeaponReady;
			Loop;
		Deselect:
			PLSG A 1 A_Lower(18);
			Loop;
		Select:
			PLSG A 1 A_Raise(18);
			Loop;
		Fire:
			PLSG A 0 A_JumpIfInventory("CocainePower", 1, "FireCocaine");
			PLSG A 4
			{
			    A_Quake(1,4,0,200);
			    A_Quake(2,4,0,250);
			}
			PLSG A 3
			{
			    A_Quake(3,3,0,300);
			    A_Quake(4,3,0,600);
			}
			PLSG A 2 A_Quake(5,2,0,800);
			PLSG A 8
			{
			    A_Quake(6,8,0,1000);
			    A_Quake(7,8,0,1200);
			}
			PLSG A 35 A_Quake(8,35,0,1600);
			PLSG A 0
			{
			    A_GunFlash();
			    A_StartSound("Sraka",0,CHANF_DEFAULT,1.0,ATTN_NONE);
			}
			PLSG A 3 A_FirePlasma;
			PLSG B 20 A_ReFire;
			Goto Ready;
		FireCocaine:
			PLSG A 2
			{
			    A_Quake(1,2,0,400);
			    A_Quake(2,2,0,500);
			    A_Quake(3,2,0,600);
			    A_Quake(4,2,0,1200);
			}
			PLSG A 1
			{
			    A_Quake(5,1,0,1600);
			    A_Quake(6,1,0,2000);
			    A_Quake(7,1,0,2400);
			}
			PLSG A 10 A_Quake(8,10,0,3200);
			PLSG A 0
			{
			    A_GunFlash();
			    A_StartSound("Sraka",0,CHANF_DEFAULT,1.0,ATTN_NONE);
			}
			PLSG A 3 A_FirePlasma;
			PLSG B 15 A_ReFire;
			Goto Ready;
		Flash:
			PLSF A 4 Bright A_Light1;
			Goto LightDone;
			PLSF B 4 Bright A_Light1;
			Goto LightDone;
		Spawn:
			PLAS A -1;
			Stop;
	}
}

CLASS PlasmaTesticle : PlasmaBall replaces PlasmaBall { 
	Default {
		Radius 13;
		Height 8;
		Speed 10;
		Damage 1;
		Projectile;
		+RANDOMIZE;
		+ZDOOMTRANS;
		+FORCEPAIN;
		RenderStyle "Add";
		Alpha 0.75;
		SeeSound "Sraka";
		DeathSound "*fist";
		Obituary "$OB_TESTICLE";
	}
	States
	{
		Spawn:
			PLSS AB 6 Bright;
			Loop;
		Death:
			PLSE ABCD 8 Bright;
			PLSE E 17 Bright;
			PLSE D 4 Bright;
			PLSE C 3 Bright;
			PLSE B 2 Bright;
			PLSE A 0 Bright A_StartSound("weapons/rocklx",0,CHANF_DEFAULT,1.0,ATTN_NONE,0.9);
			PLSE AAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 Bright A_SpawnItemEx("ThatThingThatGoesBoom",random(-25,25),random(-25,25),random(-25,25),random(-100,100),random(-100,100),random(-100,100));
			PLSE AAAAAAAAAAAAAA 0 Bright A_SpawnItemEx("ThatThingThatGoesBoom",random(-12,12),random(-12,12),random(-12,12),random(-50,50),random(-50,50),random(-50,50));
			PLSE AAAAAAAA 0 Bright A_SpawnItemEx("ThatThingThatGoesBoom",random(-6,6),random(-6,6),random(-6,6),random(-25,25),random(-25,25),random(-25,25));
			PLSE AAAA 0 Bright A_SpawnItemEx("ThatThingThatGoesBoom",random(-3,3),random(-3,3),random(-3,3),random(-10,10),random(-10,10),random(-10,10));
			PLSE AA 0 Bright A_SpawnItemEx("ThatThingThatGoesBoom",random(-1,1),random(-1,1),random(-1,1),random(-5,5),random(-5,5),random(-5,5));
			PLSE A 1 Bright A_SpawnItemEx("PlasmaNuke");
			Stop;
	}
}

CLASS PlasmaNuke : ThatThingThatGoesBoom { 
	Default {
		Scale 25.0;
		+FOILINVUL;
		+FOILBUDDHA;
		+EXTREMEDEATH;
		+FORCERADIUSDMG;
		+FORCEPAIN;
		Obituary "$OB_NUKE";
	}
	States
	{
		Spawn:
			MISL A 1 Bright;
			GoTo Death;
		Death:
			MISL B 0 Bright A_Quake(9,32,0,10000);
			MISL B 16 Bright A_Explode(100000,100000);
			MISL C 12 Bright;
			MISL D 8 Bright A_Explode(1,100000);
			Stop;
	}
}

CLASS MarineBox : RocketAmmo replaces RocketBox { 
	Default {
		Inventory.PickupMessage "$GOTMARINEBOX";
		Inventory.Amount 5;
	}
	States
	{
		Spawn:
			PLAY ABCD 6 A_SetScale(1,0.40);
			Loop;
	}
}

CLASS MarineAmmo : RocketAmmo replaces RocketAmmo { 
	Default {
		Scale 0.5;
		Inventory.PickupMessage "$GOTMARINE";
		Inventory.Amount 1;
		Inventory.MaxAmount 50;
		Ammo.BackpackAmount 1;
		Ammo.BackpackMaxAmount 100;
	}
	States
	{
		Spawn:
			PLAY ABCD 4;
			Loop;
	}
}

CLASS MarineLauncher : RocketLauncher replaces RocketLauncher { 
	Default {
		tag "Fucket Launcher";
		weapon.ammouse2 1;
		weapon.ammotype2 "rocketammo";
	}
	States
	{
		Ready:
			MISM A 0 A_JumpIfInventory("CocainePower", 1, "ReadyCocaine");
			MISM A 1 A_WeaponReady;
			Loop;
		ReadyCocaine:
			MISM C 1 A_WeaponReady;
			Loop;
		Deselect:
			MISM A 0 A_JumpIfInventory("CocainePower", 1, "DeselectCocaine");
			MISM A 1 A_Lower(18);
			Loop;
		DeselectCocaine:
			MISM C 1 A_Lower(18);
			Loop;
		Select:
			MISM A 0 A_JumpIfInventory("CocainePower", 1, "SelectCocaine");
			MISM A 1 A_Raise(18);
			Loop;
		SelectCocaine:
			MISM C 1 A_Raise(18);
			Loop;
		Fire:
			MISM A 0 A_JumpIfInventory("CocainePower", 1, "FireCocaine");
			MISM B 2 A_GunFlash;
			MISM B 6 A_FireProjectile("ImpactFucket");
			MISM B 0 A_ReFire;
			Goto Ready;
		FireCocaine:
			MISM D 2 A_GunFlash;
			MISM D 4 A_FireProjectile("ImpactNuclearFucket");
			MISM D 0 A_ReFire;
			Goto Ready;
		AltFire:
			MISM A 0 A_JumpIfInventory("CocainePower", 1, "AltFireCocaine");
			MISM B 2 A_GunFlash;
			MISM B 6 A_FireProjectile("FucketGrenadeCombo");
			MISM B 0 A_ReFire;
			Goto Ready;
		AltFireCocaine:
			MISM D 2 A_GunFlash;
			MISM D 4 A_FireProjectile("NuclearFucketGrenadeCombo");
			MISM D 0 A_ReFire;
			Goto Ready;
		Flash:
			MIMF A 3 Bright A_Light1;
			MIMF B 4 Bright;
			MIMF CD 4 Bright A_Light2;
			Goto LightDone;
	}
}

CLASS MarineGrenade : DoomWeapon { 
	Default {
		Weapon.SelectionOrder 2500;
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 1;
		Weapon.AmmoType "RocketAmmo";
		+weapon.wimpy_weapon
	}
	States
	{
		Ready:
			MNGR A 0 A_JumpIfInventory("CocainePower", 1, "ReadyCocaine");
			MNGR A 1 A_WeaponReady;
			Loop;
		ReadyCocaine:
			MNHR A 1 A_WeaponReady;
			Loop;
		Deselect:
			MNGR A 0 A_JumpIfInventory("CocainePower", 1, "DeselectCocaine");
			MNGR A 1 A_Lower(18);
			Loop;
		DeselectCocaine:
			MNHR A 1 A_Lower(18);
			Loop;
		Select:
			MNGR A 0 A_JumpIfInventory("CocainePower", 1, "SelectCocaine");
			MNGR A 1 A_Raise(18);
			Loop;
		SelectCocaine:
			MNHR A 1 A_Raise(18);
			Loop;
		Fire:
			MNGR A 0 A_JumpIfInventory("CocainePower", 1, "FireCocaine");
			MNGR ABCDDC 3;
			MNGR E 3 A_FireProjectile("FucketGrenadeGravity");
			MNGR FGH 2;
			MNGR I 2 A_ReFire;
			Goto Ready;
		FireCocaine:
			MNHR ABCDDC 2;
			MNGR E 2 A_FireProjectile("NuclearFucketGrenadeGravity");
			MNGR FG 2;
			MNHR H 2;
			MNHR I 2 A_ReFire;
			Goto Ready;
	}
}

CLASS FucketGrenadeGravity : Fucket { 
	Default {
		Speed 20;
		Gravity 0.5;
		BounceType 'Grenade';
		BounceCount 5;
		-bounceonactors;
		-NOGRAVITY;
	}
	States
	{
		Spawn:
			DEBI L 140;
			GoTo Death;
		Death:
			PLAY W 0
			{
			    A_SpawnItemEx("ThatThingThatGoesBoom");
			    A_Scream();
			}
			PLAY W -1;
			Stop;
	}
}

CLASS FucketGrenadeCombo : Fucket { 
	Default {
		Speed 48;
		Gravity 0.5;
		-NOGRAVITY;
		damagetype "none";
	}
}

CLASS NuclearFucketGrenadeGravity : FucketGrenadeGravity { 
	States
	{
		Spawn:
			DEBI M 140;
			GoTo Death;
		Death:
			PLAY W 0 Bright A_SpawnItemEx("NuclearFucketGrenadeExplosion");
			PLAY W 0 A_Scream;
			PLAY W -1;
			Stop;
	}
}

CLASS NuclearFucketGrenadeExplosion : ThatThingThatGoesBoom {
	States
	{
		Spawn:
			MISL A 1 Bright;
		Death:
			MISL WWWWWWWWWWWW 0 Bright A_SpawnItemEx("ThatThingThatGoesBoom",random(-3,3),random(-3,3),random(-3,3),random(-10,10),random(-10,10),random(-10,10));
			Stop;
	}
}

CLASS NuclearFucketGrenadeCombo : NuclearActualFucket { 
	Default {
		Speed 48;
		Gravity 0.5;
		-NOGRAVITY;
		damagetype "none";
	}
}

CLASS BadassFist : Fist {
	default {
		+weapon.wimpy_weapon
	}
	States {
		select:
			pung a 1 a_raise(18);
			loop;
		deselect:
			pung a 1 a_lower(18);
			loop;
		Fire:
			OIJG A 0 A_JumpIfInventory("CocainePower", 1, "FireCocaine");
			OIJG A 2 A_StartSound("skeleton/swing");
			OIJG BC 2;
			OIJG D 2 A_CustomPunch(random(5,15), false, 0, "BulletPuff", 70,0,0,"ArmorBonus","HOWCANSHESLAP");
			OIJG E 2;
			OIJG F 2 A_ReFire;
			Goto Ready;
		FireCocaine:
			OIJG A 1 A_StartSound("skeleton/swing");
			OIJG BC 1;
			OIJG D 1 A_CustomPunch(random(40,120), false, 0, "BulletPuff", 70,0,0,"ArmorBonus","HOWCANSHESLAP");
			OIJG E 1;
			OIJG F 1 A_ReFire;
			Goto Ready;
		AltFire:
			ZOOM A 0 A_JumpIfInventory("CocainePower", 1, "AltFireCocaine");
			ZOOM A 0 A_WeaponOffset(0.0, 32.0);
			ZOOM A 26 A_StartSound("ZUMUPANCHI");
			ZOOM A 4 A_WeaponOffset(-80.0, -80.0, WOF_ADD|WOF_INTERPOLATE);
			ZOOM A 0 A_WeaponOffset(16.0, 16.0, WOF_ADD);
			ZOOM A 2 A_CustomPunch(random(25,75), false, 0, "BulletPuff", 200);
			ZOOM A 2 A_WeaponOffset(16.0, 16.0, WOF_ADD);
			ZOOM A 4 A_WeaponOffset(0.0, 32.0, WOF_INTERPOLATE);
			PUNG A 0 A_WeaponOffset(0.0, 64.0);
			PUNG A 4 A_WeaponOffset(0.0, 32.0, WOF_INTERPOLATE);
			PUNG A 4 A_ReFire;
			Goto Ready;
		AltFireCocaine:
			ZOOM A 0 A_WeaponOffset(0.0, 32.0);
			ZOOM A 1 A_StartSound("ZUMUPANCHIcocaine");
			ZOOM A 1 A_WeaponOffset(-80.0, -80.0, WOF_ADD|WOF_INTERPOLATE);
			ZOOM A 0 A_WeaponOffset(16.0, 16.0, WOF_ADD);
			ZOOM A 1 A_CustomPunch(random(150,350), false, 0, "BulletPuff", 300);
			ZOOM A 1 A_WeaponOffset(16.0, 16.0, WOF_ADD);
			ZOOM A 2 A_WeaponOffset(0.0, 32.0, WOF_INTERPOLATE);
			PUNG A 0 A_WeaponOffset(0.0, 64.0);
			PUNG A 2 A_WeaponOffset(0.0, 32.0, WOF_INTERPOLATE);
			PUNG A 2 A_ReFire;
			Goto Ready;
	}
}

CLASS SingularBulletAmmo : Clip { 
	Default {
		Inventory.PickupMessage "$GOTSINGULARBULLET";
		Tag "Singular Bullet";
		Inventory.Amount 1;
	}
	States
	{
		Spawn:
			BULL A -1;
			Stop;
	}
}

class SpanishPistol : Pistol
{
 	Default
	{
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 20;
		Weapon.AmmoType "Clip";
		Tag "Spanish Pistol";
	}
	States
	{
	Ready:
		PSSG A 1 A_WeaponReady;
		Loop;
	Deselect:
		PSSG A 1 A_Lower(18);
		Loop;
	Select:
		PSSG A 1 A_Raise(18);
		Loop;
	Fire:
		PSSG A 0 A_JumpIfInventory("CocainePower", 1, "FireCocaine");
		PSSG B 3
		{
		   A_FireBullets (4, 2, 1, random(16,32), "BulletPuff", FBF_USEAMMO|FBF_NORANDOM);
		   A_StartSound("weapons/spanishpistol", CHAN_WEAPON, CHANF_DEFAULT, 1.0, ATTN_NORM, 0.75);
		   A_GunFlash();
		}
		PSSG B 2
		{
		   A_FireBullets (4, 2, 1, random(16,32), "BulletPuff", FBF_USEAMMO|FBF_NORANDOM);
		   A_StartSound("weapons/spanishpistol", CHAN_AUTO, CHANF_DEFAULT, 0.5, ATTN_NORM, 0.75);
		   A_GunFlash();
		}
		PSSG C 4;
		PSSG B 4 A_ReFire;
		Goto Ready;
	FireCocaine:
		PSSG B 3
		{
		   A_FireBullets (4, 2, 5, random(64,128), "BulletPuff", FBF_USEAMMO|FBF_NORANDOM);
		   A_StartSound("weapons/spanishpistol", CHAN_WEAPON, CHANF_DEFAULT, 1.0, ATTN_NORM, 0.75);
		   A_GunFlash();
		}
		PSSG B 2
		{
		   A_FireBullets (4, 2, 5, random(64,128), "BulletPuff", FBF_USEAMMO|FBF_NORANDOM);
		   A_StartSound("weapons/spanishpistol", CHAN_AUTO, CHANF_DEFAULT, 0.5, ATTN_NORM, 0.75);
		   A_GunFlash();
		}
		PSSG C 3;
		PSSG B 3 A_ReFire;
		Goto Ready;
	AltFire:
		PFSG B 0 A_JumpIfInventory("CocainePower", 1, "AltFireCocaine");
		PFSG A 0 A_WeaponOffset(0.0, 32.0);
		PFSG A 2 A_StartSound("skeleton/swing");
		PFSG AA 2 A_WeaponOffset(-64.0, 2.0, WOF_ADD);
		PFSG A 0 A_CustomPunch(random(10,15), false, 0, "BulletPuff", 70,0,0,"ArmorBonus","HOWCANSHESLAP");
		PFSG AAA 2 A_WeaponOffset(-64.0, 24.0, WOF_ADD);
		PFSG A 2 A_ReFire;
		Goto Ready;
	AltFireCocaine:
		PFSG A 0 A_WeaponOffset(0.0, 32.0);
		PFSG A 1 A_StartSound("skeleton/swing");
		PFSG AA 1 A_WeaponOffset(-64.0, 2.0, WOF_ADD);
		PFSG A 0 A_CustomPunch(random(100,150), false, 0, "BulletPuff", 70,0,0,"ArmorBonus","HOWCANSHESLAP");
		PFSG AAA 1 A_WeaponOffset(-64.0, 24.0, WOF_ADD);
		PFSG A 1 A_ReFire;
		Goto Ready;
	Flash:
		PSSF A 2 Bright A_Light1;
		Goto LightDone;
		TNT1 A 1;
		PSSF A 2 Bright A_Light1;
		Goto LightDone;
 	Spawn:
		PSST A -1;
		Stop;
	}
}

CLASS SpanishFist : Fist {
	States {
		Ready:
			PFSG B 1 A_WeaponReady;
			Loop;
		Deselect:
			PFSG B 1 A_Lower(18);
			Loop;
		Select:
			PFSG B 1 A_Raise(18);
			Loop;
		Fire:
			PFSG B 0 A_JumpIfInventory("CocainePower", 1, "FireCocaine");
			PFSG A 0 A_WeaponOffset(0.0, 32.0);
			PFSG A 2 A_StartSound("skeleton/swing");
			PFSG AA 2 A_WeaponOffset(-64.0, 2.0, WOF_ADD);
			PFSG A 0 A_CustomPunch(random(10,15), false, 0, "BulletPuff", 70,0,0,"ArmorBonus","HOWCANSHESLAP");
			PFSG AAA 2 A_WeaponOffset(-64.0, 24.0, WOF_ADD);
			PFSG A 2 A_ReFire;
			Goto Ready;
		FireCocaine:
			PFSG A 0 A_WeaponOffset(0.0, 32.0);
			PFSG A 1 A_StartSound("skeleton/swing");
			PFSG AA 1 A_WeaponOffset(-64.0, 2.0, WOF_ADD);
			PFSG A 0 A_CustomPunch(random(100,150), false, 0, "BulletPuff", 70,0,0,"ArmorBonus","HOWCANSHESLAP");
			PFSG AAA 1 A_WeaponOffset(-64.0, 24.0, WOF_ADD);
			PFSG A 1 A_ReFire;
			Goto Ready;
	}
}
