#include "zscript/weapons.zsc"
#include "zscript/cast.zsc"
#include "zscript/monsters.zsc"

CLASS BadassPlayer : DoomPlayer replaces DoomPlayer { 
	Default {
		Player.DisplayName "$PLAYER_BADASS";
		Player.StartItem "SingularBullet";
		Player.StartItem "MarineGrenade";
		Player.StartItem "BadassFist";
		Player.StartItem "Clip", 1;
		Player.StartItem "RocketAmmo", 1 ;
		Player.WeaponSlot 1, "BadassFist", "SawSaw";
		Player.WeaponSlot 2, "SingularBullet";
		Player.WeaponSlot 3, "DumbassShitFuckDickCockShotgun", "DuperShotgun";
		Player.WeaponSlot 4, "SmallButPackingChaingun";
		Player.WeaponSlot 5, "MarineGrenade", "MarineLauncher";
		Player.WeaponSlot 6, "RechargablePlasmaRifleModelv1";
		Player.WeaponSlot 7, "BCG9000";
	}
}

CLASS SpanishPlayer : BadassPlayer { 
	Default {
		Player.Face "SSF";
		Player.CrouchSprite "";
		Player.DisplayName "$PLAYER_SPANISH";
		Player.SoundClass "spanish";
		Player.StartItem "SpanishPistol";
		Player.StartItem "MarineGrenade";
		Player.StartItem "SpanishFist";
		Player.StartItem "Clip", 50;
		Player.WeaponSlot 1, "SpanishFist", "SawSaw";
		Player.WeaponSlot 2, "SpanishPistol";
	}
	States
	{
	Spawn:
		SSWV A -1;
		Loop;
	See:
		SSWV AABBCCDD 3;
		Loop;
	Missile:
		SSWV F 4;
		SSWV E 4;
		Goto Spawn;
	Melee:
		SSWV G 4 Bright;
		Goto Missile;
	Pain:
		SSWV H 3;
		SSWV H 3 A_Pain;
		Goto Spawn;
	Death:
		SSWV I 5;
		SSWV J 5 A_PlayerScream;
		SSWV K 5 A_NoBlocking;
		SSWV L 5;
		SSWV M -1;
		Stop;
	XDeath:
		SSWV O 5;
		SSWV P 5 A_XScream;
		SSWV Q 5 A_NoBlocking;
		SSWV RSTUV 5;
		SSWV W -1;
		Stop;
	}
}

CLASS NukeBarrel : ExplosiveBarrel { // 26023
	Default {
		Tag "Nuke Barrel";
	}
	States
	{
		Spawn:
			NAR1 AB 6;
			Loop;
		Death:
			NEXP A 5 Bright;
			NEXP B 5 Bright A_Scream;
			NEXP C 5 Bright;
			NEXP D 5 Bright A_SpawnItemEx("PlasmaNuke");
			NEXP E 10 Bright;
			Stop;
	}
}

class Harnas : HealthBonus replaces HealthBonus
{
	Default
	{
		Scale 0.01;
		Inventory.PickupMessage "$GOTHARNAS";
		Inventory.PickupSound "harnas/pickup";
		Tag "Harnaś (Puszka)";
	}
	States
	{
	Spawn:
		HARN A -1;
		Loop;
	}
}

class HarnasBottle : Stimpack replaces Stimpack
{
	Default
	{
		Scale 0.022;
		Inventory.PickupMessage "$GOTHARNAS";
		Inventory.PickupSound "harnasbottle/pickup";
		Tag "Harnaś";
	}
	States
	{
	Spawn:
		HARN B -1;
		Loop;
	}
}

class HarnasPack : Medikit replaces Medikit
{
	Default
	{
		Scale 0.03;
		Inventory.PickupMessage "$GOTHARNAS";
		Inventory.PickupSound "harnas/pickup";
		Tag "Harnaś (Czteropak)";
	}
	States
	{
	Spawn:
		HARN C -1;
		Loop;
	}
}

CLASS Karpackie : CustomInventory  
{
	Default {
		+COUNTITEM;
		+INVENTORY.ALWAYSPICKUP;
		Inventory.Amount 1;
		Inventory.MaxAmount 200;
		Scale 0.035;
		Tag "Karpackie";
		Inventory.PickupMessage "$GOTKARPACKIE";
		Inventory.PickupSound "harnas/pickup";
		Radius 10;
	}
	States 
	{
	Spawn:
		KARP A -1;
		Loop;
	Pickup:
		KARP A 1 A_SpawnItemEx("KarpackieEksplozja");
	}
}

CLASS KarpackieEksplozja : ACTOR 
{ 
	Default 
	{
		Radius 4;
		Height 4;
		Speed 0;
		Damage 50;
		Projectile;
		+RANDOMIZE;
		+DEHEXPLOSION;
		-ROCKETTRAIL;
		+NOEXTREMEDEATH;
		+PIERCEARMOR;
		DeathSound "Sraka";
		Obituary "$OB_KARPACKIE";
		DamageType "Karpackie";
	}
	States
	{
		Spawn:
			KARP A 1 Bright A_Scream;
			KARP A 1 Bright A_Explode(400,5,XF_THRUSTLESS|XF_HURTSOURCE);
			Stop;
	}
}

class GlassJunkNew : GlassShard replaces GlassJunk
{
	Default
	{
		-NOGRAVITY;
		-NOCLIP;
		-NOBLOCKMAP;
		Health 8;
		Speed 20;
		Gravity 0.5;
		Radius 5;
		Height 5;
	}
	States
	{
	Spawn:
		SHAR ABCDABCD 4;
		Loop;
	 Death:
		SHAR A 30;
		Stop;
	}
}

class DeathsheadFigurine : Actor
{
	States
	{
		Spawn:
			ACED A -1;
			Stop;
	}
}
